### PR TITLE
Fix #237 Javadoc typo

### LINKED ISSUE #237: Broken link in @ServerEndpoint#value() javadoc (http://http://tools.ietf.org/html/rfc6570)
Broken link in @ServerEndpoint#value() javadoc (http://http://tools.ietf.org/html/rfc6570)

### PR DESCRIPTION
**Pull request by markt-asf**

### CODE REVIEW

File: api/server/src/main/java/javax/websocket/server/ServerEndpoint.java [hunk 1]
```diff
@@ -1,5 +1,6 @@
 /*
- * Copyright (c) 2012, 2017 Oracle and/or its affiliates. All rights reserved.
+ * Copyright (c) 2012, 2017 Oracle and/or its affiliates and others.
```
Comment (bravehorsie) [inline api/server/src/main/java/javax/websocket/server/ServerEndpoint.java]: Whats the "and others" stands for? Is it some Eclipse standard to mention community contributors?  Year should be changed to 2018.

Comment (markt-asf) [reply api/server/src/main/java/javax/websocket/server/ServerEndpoint.java]: The above change (inserting ' and others') is what we are meant to do as we change files as per Eclipse Foundation guidance at https://www.eclipse.org/projects/handbook/#ip-copyright-headers
This is how the other changes made post donation have been handled.
Further advice on the ee4j-pmc list is that the years do not need to be updated.

Comment (bravehorsie) [reply api/server/src/main/java/javax/websocket/server/ServerEndpoint.java]: Thank you for explanation.
